apiVersion: v1
kind: Service
metadata:
  name: {{ include "restinthemiddle.fullname" . }}
  labels:
    {{- include "restinthemiddle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.listenPort }}
      protocol: TCP
      name: listen-port
  selector:
    {{- include "restinthemiddle.selectorLabels" . | nindent 4 }}
